networks:
  bruteforce_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  # Servidor de autenticação
  server:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.10

  # Atacante 1 de 6
  attacker_1:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt  # monta a wordlist dentro do container
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=0
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=1
      - MODE=hybrid           # hybrid | dictionary | brute
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.21
    depends_on:
      - server

  # Atacante 2 de 6
  attacker_2:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=1
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=2
      - MODE=hybrid
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.22
    depends_on:
      - server

  # Atacante 3 de 6
  attacker_3:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=2
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=3
      - MODE=hybrid
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.23
    depends_on:
      - server

  # Atacante 4 de 6
  attacker_4:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=3
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=4
      - MODE=hybrid
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.24
    depends_on:
      - server

  # Atacante 5 de 6
  attacker_5:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=4
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=5
      - MODE=hybrid
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.25
    depends_on:
      - server

  # Atacante 6 de 6
  attacker_6:
    build: .
    volumes:
      - ./wordlist.txt:/app/wordlist.txt
    environment:
      - TOTAL_ATTACKERS=6
      - ATTACKER_INDEX=5
      - SERVER_URL=http://172.20.0.10:3000/login
      - ATTACKER_ID=6
      - MODE=hybrid
      - WORDLIST_PATH=/app/wordlist.txt
    networks:
      bruteforce_net:
        ipv4_address: 172.20.0.26
    depends_on:
      - server